engines:
     fixme:
       enabled: true

ratings:
   paths:
   - "environment.monitor.api/**/*"
   - "environment.monitor.core/**/*"
   - "environment.monitor.runner/**/*"
   - "environment.monitor.plugins/**/*"
