language: java

jdk:
  - oraclejdk8

sudo: false
install: true

addons:
  sonarcloud:
    organization: "yagelnasmanit-github"
    branches:
      - master
      - develop

script:
  - mvn clean install
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'