language: java

jdk:
  - oraclejdk8

sudo: false
install: true

addons:
  sonarcloud:
    organization: "yagelnasmanit-github"
    token:
        secure: "U1QzUw//Pg7q5b+HvPxEAvtrvsgKHDz5zrLd4Os2o54kqQipUQut3VAb/HX2gUqvsWV3NWeHPFeysTs23NDEVep7YfmUeOpuUxuoi4Y7xQ5gvZRubA0Z7WxQbv6ubwIdjfO5lJd905u0r2RKNNVrz2z/cbhqhR4nOAKg8jqYw0wOg1+KbjYl8wXE3LT0zbee9HKoY0IpZjZy3MgPIfcjPafa7fjrEZsIpy3wjFDpkIYLOxfZcd9j94XfiOj4o54vqXfRa62aBgID39YCe/Es3JGv6Cc17pKwQf4CWI5qLfEq8oYtZsbLsDdWtfLzvACVVwG4UujChphW58LVuWVrc0wWXFoQGiApcO3TMgMUpOwlsf9mvs3nMJjQ274SJba7rzeZzKKKVMaq8ZaD7LGVBCRR92nwBTE3lzr3AHbHEEOPQ5fIZbxSZyR2B7CPcaoJshwAfYYJK+gYkXshUWjzs75KgJMgcmvEnuXzAMw+70Mmjkv9EUcrW4BOS8aJRuvHRGK8YDnk5z3Z0I1+rxc8Yughq+LbooIQRSmreRoAB7izSpvZerRVgdbQG1wfCKFomlxrwrfkQc28C7NUSZImswHQyhAjWUePfLXds3vo+VerAuRB+1hN3FgN42ssVSbAL2q39kP8aZWc4lC6eOCqhjdXVsw33wcfKWZCqrFWUdQ="
    branches:
      - master
      - develop

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar


cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'