language: java

jdk:
  - oraclejdk8

sudo: false
install: true

addons:
  sonarcloud:
    organization: "yagelnasmanit-github"
    token:
          secure: "lp+6amP6RxisCrV2/GrUapdgHpSvk8cSzUIVvn5hUo1aTWhMq8y58wbdlCH1Ip4JwT6m4dJFsXuZENRxdBFjIQ54IJ69Cuc7Iq6DuWxPaFH3CQ/J0i6Tbp3gyPAH8M1qxvENHGWxESvJR6es8Afz6RsV6Reo7uM3psRZB0C7DJSSSsXJEDaSvupFbRh/PWlfobJNAz4at5mNQRjeGS3Ke9eYDPMQ8AMxupXHHw66aKlxW9WlAK0OHP3P2ah5fyf4En7XHMTwjNLc0KS3yD0CKgAfKmwIBZ4u+bgah4Qi4xAJ684PZx5YwlwLydi6qWlccMZwpQhuYurzGCuwwVZ3jYW/Y0HVDyWnPB1vGVAIdtdtnyBB2SnVsnDjwOhf6EzyDV1R5h713g3Jb5zp8Z3SrdczF58Aqy35FigqpI0LEKjC0fgJOZaWnEFCPNoudStq+FXV6k0jca0TbQ+r6xtsx/7C+cLcG774x3fYvwf8z0teAkddHNuOq7zW/s5d8TnUWMJA30BIzQrvo/i0J/B2pGW3kbiRhF75lBSF8swLzrA+nK/zlQ1gK661V6AovBhKsmPUT4VzuwpmCRfSDGCiJ0p1gZvaiqroUp1Hk5V7R6h5qYkZz1EpaMikyUFB/H8fyeOn4LDawuxqBMekHznI0kT0LgO1tQDU7KaJoE85lh0="
    branches:
      - master
      - develop

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar


cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'